import { BRAND } from "@/lib/brand/site";
import { ZONE_ORIGINS } from "@/lib/routing/zones";

/**
 * Canonical public origin for SEO (canonical tags, OG, sitemap, robots, schema).
 * Always the marketing zone — never the app/auth subdomains — so indexable URLs
 * stay on cliniqflow.app.
 */
export const SITE_URL = ZONE_ORIGINS.marketing;

export const SITE_NAME = BRAND.nameDisplay;

export const DEFAULT_DESCRIPTION = BRAND.positioning;

/** Generated by src/app/opengraph-image.tsx */
export const OG_IMAGE_PATH = "/opengraph-image";

export const OG_IMAGE_ALT =
  "CliniqFlow — patient intake and documentation workflow software for clinics";
